version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: hr_system_db
      POSTGRES_USER: hr_system_user
      POSTGRES_PASSWORD: hr_system_pwd

volumes:
  postgres_data: